import type { Category } from "./types"

export const mockCategories: Category[] = [
  {
    id: "CAT-001",
    name: "Electronics",
    parentId: null,
    description: "Electronic devices and accessories",
    imageUrl: "",
    status: "active",
    sortOrder: 1,
    productsCount: 150,
    level: 0,
  },
  {
    id: "CAT-002",
    name: "Computers",
    parentId: "CAT-001",
    description: "Desktop and laptop computers",
    imageUrl: "",
    status: "active",
    sortOrder: 1,
    productsCount: 45,
    level: 1,
  },
  {
    id: "CAT-003",
    name: "Laptops",
    parentId: "CAT-002",
    description: "Portable laptop computers",
    imageUrl: "",
    status: "active",
    sortOrder: 1,
    productsCount: 30,
    level: 2,
  },
  {
    id: "CAT-004",
    name: "Smartphones",
    parentId: "CAT-001",
    description: "Mobile phones and accessories",
    imageUrl: "",
    status: "active",
    sortOrder: 2,
    productsCount: 80,
    level: 1,
  },
  {
    id: "CAT-005",
    name: "Clothing",
    parentId: null,
    description: "Apparel and fashion items",
    imageUrl: "",
    status: "active",
    sortOrder: 2,
    productsCount: 200,
    level: 0,
  },
  {
    id: "CAT-006",
    name: "Men's Wear",
    parentId: "CAT-005",
    description: "Clothing for men",
    imageUrl: "",
    status: "active",
    sortOrder: 1,
    productsCount: 90,
    level: 1,
  },
  {
    id: "CAT-007",
    name: "Women's Wear",
    parentId: "CAT-005",
    description: "Clothing for women",
    imageUrl: "",
    status: "inactive",
    sortOrder: 2,
    productsCount: 110,
    level: 1,
  },
]
